# Generated by Django 2.2.1 on 2019-05-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=10)),
                ('user_Id', models.CharField(max_length=50)),
                ('mobileNumber', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
